---

- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Install Java
  package:
    name: "{{ JAVA }}"
    state: present

- name: Download gatk
  get_url:
    url: "https://software.broadinstitute.org/gatk/download/auth?package=GATK"
    dest: "/home/{{ ATMOUSERNAME }}/gatk.tar.bz2"

- name: Unarchive gatk
  unarchive:
    src: "/home/{{ ATMOUSERNAME }}/gatk.tar.bz2"
    dest: "/home/{{ ATMOUSERNAME }}"
    remote_src: yes

- name: Add small readme
  lineinfile:
    state: present
    create: yes
    path: "/home/{{ ATMOUSERNAME }}/GenomeAnalysisTK-README.txt"
    line: "To get info on how to use the program, type 'java -jar /path/to/GenomeAnalysisTK.jar -h'"

- name: Cleanup temporary files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/home/{{ ATMOUSERNAME }}/gatk.tar.bz2"
    - "/home/{{ ATMOUSERNAME }}/resources"
